CREATE DATABASE CRUD_N_CAPAS
	GO
	USE CRUD_N_CAPAS
	CREATE TABLE PERSONAS (
	ID  INT PRIMARY KEY NOT NULL,
	Nombre varchar(250) NULL,
	Apellido  varchar(250) NULL,
	Sexo NVARCHAR(12)
	
	);
	SELECT * FROM PERSONAS